CREATE TABLE IF NOT EXISTS bronze_health (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inserted_at TIMESTAMPTZ DEFAULT NOW(),
    raw_payload JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS bronze_journal (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inserted_at TIMESTAMPTZ DEFAULT NOW(),
    raw_payload JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS bronze_music (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inserted_at TIMESTAMPTZ DEFAULT NOW(),
    raw_payload JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS bronze_screentime (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inserted_at TIMESTAMPTZ DEFAULT NOW(),
    raw_payload JSONB NOT NULL
);
